SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
FPS = 60

BIRD_SIZE = 34
PIPE_WIDTH = 52
PIPE_GAP = 150

GRAVITY = 0.5
JUMP_STRENGTH = 8
PIPE_SPEED = 3
BIRD_X = 20

BASE_HEIGHT = 100

ASSET_PATH = "assets/"
BIRD_IMG = ASSET_PATH + "bird.png"
PIPE_IMG = ASSET_PATH + "pipe.png"
BG_IMG = ASSET_PATH + "background.png"
BASE_IMG = ASSET_PATH + "base.png"